CHOST="x86_64-pc-linux-gnu"
x86_64_pc_linux_gnu_CFLAGS="-march=core2 -pipe -O2"
x86_64_pc_linux_gnu_CXXFLAGS="-march=core2 -pipe -O2"
x86_64_pc_linux_gnu_LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
i686_pc_linux_gnu_CFLAGS="-march=core2 -pipe -O2"
i686_pc_linux_gnu_CXXFLAGS="-march=core2 -pipe -O2"
i686_pc_linux_gnu_LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"

[[ -e /etc/paludis/hooks/setup_pkg_env.bash ]] && . /etc/paludis/hooks/setup_pkg_env.bash

